import '../globals.css'
import Navbar from '../containers/Navbar/Navbar';
import Footer from '../containers/Footer/Footer';

export const metadata = {
  title: 'Tietgenkollegiet',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <div>
        {children}
      </div>
  )
}
